# Generated by Django 4.2.3 on 2023-07-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao', models.DecimalField(decimal_places=0, max_digits=14)),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrega', models.DateField(auto_now_add=True)),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cesta')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.funcionario')),
            ],
        ),
    ]
